name: Update Playlist Data

on:
  schedule:
    # At 12:00pm on Sunday, Monday, and Wednesday
    - cron: '0 12 * * 0,1,3'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        persist-credentials: false
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd scraper && npm ci
    - run: cd scraper && npm start

    - name: Commit changes
      run: |
        git config --local user.email "811945+patrickgalbraith@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data
        git diff-index --quiet --cached HEAD || git commit -m "Update playlist data $(date +'%Y-%m-%dT%H:%M:%S')"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
